method: random

metric:
  name: val_accuracy
  goal: maximize

parameters:
  epochs:
    value: 60
  weight_decay:
    values: [0.0001, 0.001, 0.01]
  l_e:
    values: [5, 10, 15]   # max epoch for linear warm-up of lambda
  l_b:
    values: [0.96, 0.97, 0.98, 0.99] # base for exponential decay of lambda
  lr:
    values: [0.01, 0.001, 0.0001, 0.00001, 0.000001]
  batch_size:
    values: [64, 128, 256, 512, 1024]
  scheduler:
    value: LambdaLR
  optimizer:
    value: adam
  num_classes:
    value: 15
  split:
    value: train/val/test
  dropout:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  device:
    value: cuda